### ISSUE TITLE
When testing,  feature list is empty

### ISSUE THREAD

**Issue by zhang123-sys** [IrvingMeng/MagFace#54]
![image](https://user-images.githubusercontent.com/63956071/202697773-73f35203-4519-49fe-9955-74aea7086be3.png)

**Comment by zhang123-sys** [comment]
root@Idddbe339d00c011ff:/hy-nas/MagFace-main/eval/eval_recognition# ./eval.sh lfw/cfp/agedb/magface_iresnet18_casia_dp.pth official 18
Traceback (most recent call last):
  File "../../inference/gen_feat.py", line 6, in <module>
    from utils import utils
  File "/hy-nas/MagFace-main/eval/eval_recognition/../../utils/__init__.py", line 1, in <module>
    from .utils import utils
  File "/hy-nas/MagFace-main/eval/eval_recognition/../../utils/utils.py", line 17, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
Traceback (most recent call last):
  File "../../inference/gen_feat.py", line 6, in <module>
    from utils import utils
  File "/hy-nas/MagFace-main/eval/eval_recognition/../../utils/__init__.py", line 1, in <module>
    from .utils import utils
  File "/hy-nas/MagFace-main/eval/eval_recognition/../../utils/utils.py", line 17, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
Traceback (most recent call last):
  File "../../inference/gen_feat.py", line 6, in <module>
    from utils import utils
  File "/hy-nas/MagFace-main/eval/eval_recognition/../../utils/__init__.py", line 1, in <module>
    from .utils import utils
  File "/hy-nas/MagFace-main/eval/eval_recognition/../../utils/utils.py", line 17, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
evaluate lfw
Traceback (most recent call last):
  File "eval_1v1.py", line 153, in <module>
    main()
  File "eval_1v1.py", line 150, in main
    perform_1v1_eval(args)
  File "eval_1v1.py", line 49, in perform_1v1_eval
    feat_pairs = load_feat_pair(feat_list, pair_list)
  File "eval_1v1.py", line 35, in load_feat_pair
    with open(feat_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: './features/magface_iresnet18//lfw_official.list'
evaluate cfp
Traceback (most recent call last):
  File "eval_1v1.py", line 153, in <module>
    main()
  File "eval_1v1.py", line 150, in main
    perform_1v1_eval(args)
  File "eval_1v1.py", line 49, in perform_1v1_eval
    feat_pairs = load_feat_pair(feat_list, pair_list)
  File "eval_1v1.py", line 35, in load_feat_pair
    with open(feat_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: './features/magface_iresnet18//cfp_official.list'
evaluate agedb
Traceback (most recent call last):
  File "eval_1v1.py", line 153, in <module>
    main()
  File "eval_1v1.py", line 150, in main
    perform_1v1_eval(args)
  File "eval_1v1.py", line 49, in perform_1v1_eval
    feat_pairs = load_feat_pair(feat_list, pair_list)
  File "eval_1v1.py", line 35, in load_feat_pair
    with open(feat_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: './features/magface_iresnet18//agedb_official.list'

**Comment by IrvingMeng** [comment]
Hi, the first error is _ModuleNotFoundError: No module named 'loguru'_. Installing the package may fix the issue.

**Comment by zhang123-sys** [comment]
![image](https://user-images.githubusercontent.com/63956071/204184614-cfbbd7c8-0ff7-4192-ba3c-31c02ad18a2d.png)
pip install loguru
but 
ImportError: cannot import name 'utils' from 'utils.utils' (/hy-nas/MagFace-main/eval/eval_recognition/../../utils/utils.py)
